### ISSUE TITLE
download PDF button doesn't work from desktop

### ISSUE THREAD

**Issue by bcooney** [JoyNeop/yart#1]
Hi there,

I just downloaded YART as a .zip to my desktop to begin working with the files. After changing the information and saving my local .html file, I opened it in my browser and found the "download PDF" button at the top does not work. It opens a new window, but nothing else. 

In the local copy, the "download PDF" button points to file:///resume/brendancooney_resume.pdf (based on the filename I gave the PDF on line 38 of the html code)

I am using Firefox 40, and edited with SublimeText2. 

I thought that this button would trigger the browsers PDF viewing mode, as your readme says "...this functionality is provided in browser's printing feature."

Any ideas on what I'm doing wrong that this feature doesn't work locally? Thanks a lot.

**Comment by neruthes** [comment]
Nah as implied in README... You are supposed to generate a PDF from the webpage manually. Almost every modern browser supports printing and @print CSS rules.

Please be advised that this is a framework which lets you critically reduce your own work in creating a web-based resume; not a one-station magic which solves all the things magically.

**Comment by bcooney** [comment]
thanks for clarifying :)
